
// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as AuthenticateRouteImport } from './routes/authenticate'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateSettingsUserRouteImport } from './routes/_private/settings-user'
import { Route as PrivateRelatoryMonthsRouteImport } from './routes/_private/relatory-months'
import { Route as PrivatePixTranfereRouteImport } from './routes/_private/pix-tranfere'

const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticateRoute = AuthenticateRouteImport.update({
  id: '/authenticate',
  path: '/authenticate',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateSettingsUserRoute = PrivateSettingsUserRouteImport.update({
  id: '/settings-user',
  path: '/settings-user',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateRelatoryMonthsRoute = PrivateRelatoryMonthsRouteImport.update({
  id: '/relatory-months',
  path: '/relatory-months',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivatePixTranfereRoute = PrivatePixTranfereRouteImport.update({
  id: '/pix-tranfere',
  path: '/pix-tranfere',
  getParentRoute: () => PrivateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/authenticate': typeof AuthenticateRoute
  '/routes': typeof RoutesRoute
  '/pix-tranfere': typeof PrivatePixTranfereRoute
  '/relatory-months': typeof PrivateRelatoryMonthsRoute
  '/settings-user': typeof PrivateSettingsUserRoute
}
export interface FileRoutesByTo {
  '/authenticate': typeof AuthenticateRoute
  '/routes': typeof RoutesRoute
  '/pix-tranfere': typeof PrivatePixTranfereRoute
  '/relatory-months': typeof PrivateRelatoryMonthsRoute
  '/settings-user': typeof PrivateSettingsUserRoute
  '/': typeof PrivateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/authenticate': typeof AuthenticateRoute
  '/routes': typeof RoutesRoute
  '/_private/pix-tranfere': typeof PrivatePixTranfereRoute
  '/_private/relatory-months': typeof PrivateRelatoryMonthsRoute
  '/_private/settings-user': typeof PrivateSettingsUserRoute
  '/_private/': typeof PrivateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticate'
    | '/routes'
    | '/pix-tranfere'
    | '/relatory-months'
    | '/settings-user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/authenticate'
    | '/routes'
    | '/pix-tranfere'
    | '/relatory-months'
    | '/settings-user'
    | '/'
  id:
    | '__root__'
    | '/_private'
    | '/authenticate'
    | '/routes'
    | '/_private/pix-tranfere'
    | '/_private/relatory-months'
    | '/_private/settings-user'
    | '/_private/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  AuthenticateRoute: typeof AuthenticateRoute
  RoutesRoute: typeof RoutesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticate': {
      id: '/authenticate'
      path: '/authenticate'
      fullPath: '/authenticate'
      preLoaderRoute: typeof AuthenticateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/settings-user': {
      id: '/_private/settings-user'
      path: '/settings-user'
      fullPath: '/settings-user'
      preLoaderRoute: typeof PrivateSettingsUserRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/relatory-months': {
      id: '/_private/relatory-months'
      path: '/relatory-months'
      fullPath: '/relatory-months'
      preLoaderRoute: typeof PrivateRelatoryMonthsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/pix-tranfere': {
      id: '/_private/pix-tranfere'
      path: '/pix-tranfere'
      fullPath: '/pix-tranfere'
      preLoaderRoute: typeof PrivatePixTranfereRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivatePixTranfereRoute: typeof PrivatePixTranfereRoute
  PrivateRelatoryMonthsRoute: typeof PrivateRelatoryMonthsRoute
  PrivateSettingsUserRoute: typeof PrivateSettingsUserRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivatePixTranfereRoute: PrivatePixTranfereRoute,
  PrivateRelatoryMonthsRoute: PrivateRelatoryMonthsRoute,
  PrivateSettingsUserRoute: PrivateSettingsUserRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  AuthenticateRoute: AuthenticateRoute,
  RoutesRoute: RoutesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
